version: '3'
services:
  server:
    build: .
    ports:
    - "22005:22005"
    - "22006:22006"
    depends_on:
    - db
  
  db:
    image: mariadb:latest
    volumes: 
      - dbData:/var/lib/mysql
    restart: always
    ports: 
    - "10106:3306"
    environment:
       MYSQL_ROOT_PASSWORD: rootpassword
       MYSQL_DATABASE: project-san-andreas
       MYSQL_USER: psa-user
       MYSQL_PASSWORD: psa-user-pwd
volumes:
  dbData: {}
    
