version: '3'
services:
  server:
    build: .
    ports:
    - "22005:22005"
    - "22006:22006"
    depends_on:
    - db
  
  db:
    image: mariadb:latest
    volumes: 
      - dbData:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci', '--wait-timeout=6000', '--connect-timeout=6000', '--max-allowed-packet=512M', '--max-connections=10']
    ports: 
    - "10106:3306"
    environment:
       MYSQL_ROOT_PASSWORD: rootpassword
       MYSQL_DATABASE: project-san-andreas
       MYSQL_USER: psa-user
       MYSQL_PASSWORD: psa-user-pwd
volumes:
  dbData: {}
    
